sudo: required
services:
  - docker
  

before_install:
  - docker build -t himanshu5692/docker-react -f Dockerfile.dev .
  

script:
  - docker run -e CI=true himanshu5692/docker-react npm run test -- --coverage

