version: '3'
services:
  react-app1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /usr/react1/node_modules
      - .:/usr/react1
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /usr/react1/node_modules
      - .:/usr/react1
    command: ["npm","run","test"]
